// Code generated by hero.
// source: /Users/mongmx/workspace/go/src/github.com/mongmx/sse-redis/templates/admin/test.html
// DO NOT EDIT!
package t

import (
	"io"

	"github.com/shiyanhui/hero"
)

func ViewTestPage(w io.Writer) (int, error) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <title>Alpine and SSE</title>
</head>

<body>
    <h1>Layout</h1>
    `)
	_buffer.WriteString(`
    this is test page
    <div x-data="dataD()" x-init="mounted()">
        <p x-show.transition="sseResponse">
            <p x-text="sseResponse.id"></p>
            <p x-text="sseResponse.name"></p>
            <p x-text="sseResponse.category"></p>
            <p x-text="sseResponse.qty"></p>
        </p>
    </div>
`)

	_buffer.WriteString(`
    <script>
        function dataD() {
            return {
                sseResponse: '',
                mounted() {
                    const self = this;
                    const eventSource = new EventSource("http://localhost:8080/products/streams/966cfb17-5891-43d4-a205-0bc53938a9e4");
                    eventSource.addEventListener('product update', function (event) {
                        self.sseResponse = JSON.parse(event.data);
                    });
                }
            }
        }
    </script>
`)

	_buffer.WriteString(`
</body>

</html>`)
	return w.Write(_buffer.Bytes())

}
