// Code generated by hero.
// source: /Users/mongmx/workspace/go/src/github.com/mongmx/sse-redis/templates/user/userlist.html
// DO NOT EDIT!
package t

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func ViewUserList(userList []string, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <title>Alpine and SSE</title>
</head>

<body>
    <h1>Layout</h1>
    `)
	for _, user := range userList {
		buffer.WriteString(`
        <ul>
            `)
		buffer.WriteString(`<li>
    `)
		hero.EscapeHTML(user, buffer)
		buffer.WriteString(`
</li>
`)
		buffer.WriteString(`
        </ul>
    `)
	}

	buffer.WriteString(`
</body>

</html>`)

}
