// Code generated by hero.
// source: /Users/mongmx/workspace/go/src/github.com/mongmx/sse-redis/templates/user/userlistwriter.html
// DO NOT EDIT!
package t

import (
	"io"

	"github.com/shiyanhui/hero"
)

func ViewUserListToWriter(userList []string, w io.Writer) (int, error) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <title>Alpine and SSE</title>
</head>

<body>
    <h1>Layout</h1>
    `)
	for _, user := range userList {
		_buffer.WriteString(`
        <ul>
            `)
		_buffer.WriteString(`<li>
    `)
		hero.EscapeHTML(user, _buffer)
		_buffer.WriteString(`
</li>
`)
		_buffer.WriteString(`
        </ul>
    `)
	}

	_buffer.WriteString(`
</body>

</html>`)
	return w.Write(_buffer.Bytes())

}
