development:
  dialect: postgres
  datasource: host=db dbname=streamline user=docker password=docker sslmode=disable
  dir: postgres
  table: migrations

localhost:
  dialect: postgres
  datasource: host=127.0.0.1 dbname=streamline user=mongmx sslmode=disable
  dir: postgres
