// Code generated by hero.
// source: github.com/mongmx/sse-redis/domain/admin/template/test.html
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/shiyanhui/hero"
)

func ViewTestPage(w io.Writer) (int, error) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        <h1>Layout</h1>
        `)
	_buffer.WriteString(`
    this is test page
`)

	_buffer.WriteString(`
    </body>
</html>
`)
	return w.Write(_buffer.Bytes())

}
