// Code generated by hero.
// source: github.com/mongmx/sse-redis/domain/admin/template/userlist.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func UserList(userList []string, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        <h1>XXXXXXXXXXX</h1>
        `)
	for _, user := range userList {
		buffer.WriteString(`
        <ul>
            `)
		buffer.WriteString(`<li>
    `)
		hero.EscapeHTML(user, buffer)
		buffer.WriteString(`
</li>
`)
		buffer.WriteString(`
        </ul>
    `)
	}

	buffer.WriteString(`
    </body>
</html>
`)

}
